[package]
name = "ere-sp1"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkvm-interface = { workspace = true }
build-utils.workspace = true
sp1-sdk = "5.0.5"
tempfile = "3.3"
bincode = "1.3"
thiserror = "2"
tracing = "0.1"

[build-dependencies]
build-utils.workspace = true

[lib]
name = "ere_succinct"
path = "src/lib.rs"
